# Plot parameter
number_points: 2000

waist_vs: 'dc'

cmap_name: 'gray'
alpha: 0.8

plot_bandwidth: False
plot_waist: True
plot_pump_power: False
squeezing_wavelength: False
plot_threshold: False
plug_value: False

# Wavelength
wavelength: 780e-9

# Cavity parameters
fixed_length: 700e-3
fixed_d_curved: 190e-3
min_L: 200e-3
max_L: 900e-3
cavity_loss: 0.03
d_curved_min: 50e-3
d_curved_max: 200e-3

# Transmission coefficients
min_T: 0.
max_T: 0.3
R: 100e-3

# Bandwidth
central_freq: 10.0e6
range_freq: 0.1

# Crystal parameters
crystal_length: 20e-3
crystal_index: 1.84  # PPKTP refraction index

# Squeezing parameters
omega_c: 10000000.0               # bandwidth of the cavity
threshold: 1.0