# Plot parameter
number_points: 500

cmap_name: 'autumn'
alpha: 0.8

plot_bandwidth: True
plot_waist: False
plot_kaertner: False

# Wavelength
wavelength: 780e-9

# Cavity parameters
fixed_length: 600e-3
min_L: 0.1
max_L: 4.
cavity_loss: 0.01
d_curved_min: 0
d_curved_max: 100e-3

# Transmission coefficients
min_T: 0.
max_T: 0.99
R: 50e-3
R1: 10e-2  # for Kaertner plot
R2: 11e-2  # for Kaertner plot

# Bandwidth
central_freq: 1.0e6
range_freq: 0.1

# Crystal parameters
crystal_length: 10e-3
crystal_index: 1.8396  # PPKTP refraction index

# Squeezing parameters
omega_c: 65000000.0               # bandwidth of the cavity
threshold: 1.0